### ISSUE TITLE
Using a script to start vim instead of environment variable

### ISSUE THREAD

**Issue by WnndGws** [ammgws/dotfiles#6]
Using [a script](https://github.com/ammgws/dotfiles/blob/master/fish/.config/fish/functions/vim.fish) to run vim. 

You can set the env variable `VIMINIT=":source $XDG_CONFIG_HOME/vim/vimrc"` instead.

**Comment by ammgws** [comment]
I wanted a separate config for neovim hence using wrapper.

Anyway I just performed a cleanup of my functions and vim is now gone since not using it anymore.

**Comment by WnndGws** [comment]
It's the best I had
